apiVersion: apps/v1
kind: Deployment
metadata:
  name: company
  labels:
      app: company
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company
  template:
    metadata:
      name: company
      labels:
        app: company
    spec:
      containers:
      - name: company
        image: suryakant100/company-ms:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 9091
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
      restartPolicy: Always    
